### ISSUE TITLE
Associate lemmata that are the same word regardless of whether they have macrons

### ISSUE THREAD

**Issue by IvyJL** [Hedera-Lang-Learn/hedera#104]
vīvō “to live, be alive” and vivo “to live, be alive, have life” should be treated as the same in terms of whether the learner knows the word. Is it possible this process could be automated looking for overlap in the definitions?

Unlike ignoring the macrons completely, that would still allow us to use them to distinguish things like ōs “mouth” and os “bone”.

**Comment by jtauber** [comment]
This might largely be solvable in the spreadsheet.

**Comment by IvyJL** [comment]
I don’t think this is very feasible to do in the spreadsheet. It’s not just a question of doubling everything (macroned and macronless variants). Let’s say I’m authoring a text and I just leave out one macron on a word with two macrons. Now we’re up to 4 variants. Longer words will have exponentially more possible permutations. 

Even if we leave aside author error or other errors in sources, there isn’t universal agreement about whether some things should have a macron or not, so again we start multiplying variants. 

Would it be hard to just ignore diacritics in lemmatizing so that fēmina and femina are recognized as the same word?

**Comment by jtauber** [comment]
Good points! I take back my spreadsheet suggestion :-)

**Comment by jtauber** [comment]
With the change I made for #160, we'll be ignoring macrons when lemmatizing Latin. I'm not sure this addresses all aspects of this issue but we can discuss.

**Comment by IvyJL** [comment]
This is working in that, e.g., amō and amo will both be lemmatized the same way, regardless of one having the macron! 
So I'm going to close this now. If something comes up in further testing, I'll reopen.
