### ISSUE TITLE
improve database query efficiency when checking text against vocabulary list

### ISSUE THREAD

**Issue by jtauber** [Hedera-Lang-Learn/hedera#109]
a 409-token Latin text I tried was doing 3313 database queries (taking 3 seconds) to evaluate against DCC list

**Comment by paltman** [comment]
#256 takes a 391-token Latin text down from 2206 queries to 601 to eval against DCC

**Comment by paltman** [comment]
we can drop the 601 down a LOT, I think just by caching:

```python
    def related_nodes(self, up=True, down=True):
        nodes = [self]
        if self.children.count() == 1 and down:
            child = self.children.first()
            nodes += child.related_nodes(up=False)
        if self.parents.count() > 0 and up:
            for parent in self.parents.all():
                nodes += parent.related_nodes(down=False)
        return nodes
```

I was thinking caching this by just setting a field on `LatticeNode` to store the space delimited list of PKs but I'm not yet clear on when to clear/invalidate it.  Didn't want to block this improvements from going out.  It's worth a second pass to do this, though.
