### ISSUE TITLE
Unknown words issue

### ISSUE THREAD

**Issue by bilbe** [Hedera-Lang-Learn/hedera#128]
I'm guess that the word is not in Ivy's list or Logeion's it is defaulting to some random list of words (compare screenshots below). See this example from Dev: https://dev.hederaproject.org/lemmatized_text/77/

![image](https://user-images.githubusercontent.com/5712116/70155710-c41bc280-1680-11ea-89cb-d031f8408f0f.png)

![image](https://user-images.githubusercontent.com/5712116/70155760-d7c72900-1680-11ea-9692-59b0616e306d.png)

**Comment by jtauber** [comment]
looks like there's no lemma at all (note that after the red lattice node number there's nothing before the "from morpheus" gloss).

I suspect we just need to not include the lemma on the token if the lemma is ""!

**Comment by IvyJL** [comment]
Something weird is going on with capitalized words that are not at the start of a sentence. Philomela is actually in Morpheus.

A quick-and-dirty solution would be to ignore all capitalized words (Latin doesn't have to use caps at the start of a sentence)

Best,
Ivy

**Comment by jtauber** [comment]
@bilbe can you paste the actual text you used in the screenshots so I can test locally?

**Comment by jtauber** [comment]
I'm wondering if this is a data issue now fixed. I just tried entering the text "Eois lanieter" and it came back red (i.e. not lemmatised) rather than the situation shown in your screenshots.

**Comment by bilbe** [comment]
Psittacus, Eois imitatrix ales ab Indis,
occidit—exequias ite frequenter, aves!
ite, piae volucres, et plangite pectora pinnis
et rigido teneras ungue notate genas;
horrida pro maestis lanieter pluma capillis,
pro longa resonent carmina vestra tuba!
quod scelus Ismarii quereris, Philomela, tyranni,
expleta est annis ista querela suis;
alitis in rarae miserum devertere funus—
magna, sed antiqua est causa doloris Itys.

**Comment by bilbe** [comment]
This seems much better... at least in the Teacher's version. When I go to the student version locally, I still don't get the dots and the ability to select 1-5. It is working in Dev at least some of the time.

**Comment by bilbe** [comment]
I'm going to close this out. Remaining issues are in #136
