### ISSUE TITLE
Ability to rank words in Learner mode has disappeared 

### ISSUE THREAD

**Issue by bilbe** [Hedera-Lang-Learn/hedera#129]
Ability to rank words in Learner mode has disappeared

https://dev.hederaproject.org/lemmatized_text/77/learner/

**Comment by jtauber** [comment]
The link is unfortunately not helpful because it's restricted to the user.

By "ability to rank", do you mean give the familiarity?

It's working for me...

<img width="1214" alt="Screen Shot 2019-12-04 at 10 47 02 AM" src="https://user-images.githubusercontent.com/24426/70157383-7c4a6a80-1683-11ea-8388-ae6647b4ae20.png">

**Comment by bilbe** [comment]
Yes. So it didn't work for the first three words in my text. Sorry, it works for many of the rest of the words. The first word _Psittacus_ (parrot), is in the logeion list, as is _imitatrix_ (she that imitates) so it shows up in the teachers version. but not in the learner version, so that is an issue.

**Comment by bilbe** [comment]
ALSO _ab_ is not showing up in the learner version, even thought I disambiguated it in the teacher version, see below.

![image](https://user-images.githubusercontent.com/5712116/70158132-be27e080-1684-11ea-832d-0bbc7602c8ad.png)
![image](https://user-images.githubusercontent.com/5712116/70158191-d435a100-1684-11ea-859e-9c63bbd3dd5a.png)

**Comment by bilbe** [comment]
I'm also noticing that it is not remembering my rankings in the learner interface, but is in my personal vocabulary list.

**Comment by IvyJL** [comment]
Hi,

I was able to specify familiarity in the Learner mode.
Then I changed my level of familiarity in my Personal Word lIst.
And the change showed up when I went back to the Learner mode.

Best,
Ivy

**Comment by bilbe** [comment]
I reloaded my page and the words I ranked before are showing up, but any new ones disappear from the interface once I move away from the word and come back. I'm I the only one experiencing that?

**Comment by IvyJL** [comment]
I am getting that too. If I rank familiarity in Learner mode, move to a new word, and then move back to the ranked word, the familiarity is "forgotten" in the Learner mode.
But if I go to my Personal Word List, the familiarity rank is actually there.
Even weirder, when I go back to Learner mode, the "forgotten" familiarity is now "remembered"
It's like you need to stop by your Personal Word List to get the familiarity to stick.

Best,
Ivy
