### ISSUE TITLE
some words not lemmatizing for unclear reasons

### ISSUE THREAD

**Issue by IvyJL** [Hedera-Lang-Learn/hedera#135]
saltant, tyranni, de 
none very obscure and _de_ very common

**Comment by bilbe** [comment]
![image](https://user-images.githubusercontent.com/5712116/71187625-6aed8a80-224d-11ea-9dca-4d7e00aef7c2.png)

**Comment by jtauber** [comment]
I can confirm that none of saltant tyranni de currently lemmatise. I'm just going to see if morpheus is returning anything at all for them.

**Comment by IvyJL** [comment]
Adding _principio_ to the list for the record

**Comment by jtauber** [comment]
Testing against the raw Morphology API:

saltant: []
tyranni: ['tyrannus']
de: ['de']
principio: ['principio', 'principium']

So other than saltant, the problem lies elsewhere. Investigating further...

**Comment by jtauber** [comment]
Still in progress, but just to update with the latest findings: the issue seems to be not that the lemmatizer didn't know the word but rather that once the lemma came back, it was not in the lattice (and we changed things to prevent the lemmatizer from creating new nodes except to handle ambiguity).

So the underlying issue is probably that Logeion doesn't have the lemmas tyrannus or de (although I don't know why yet and need to confirm).

**Comment by jtauber** [comment]
I can confirm my suspicions from two weeks ago:

1. morpheus does not recognise saltant
2. logeion doesn't have tyrannus
3. logeion doesn't have de
4. while morpheus thinks principio is ambiguous, logeion only has principium as a lemma

but also note:

5. morpheus does not recognise prīncipīo with macrons

**Comment by IvyJL** [comment]
I don't understand how logeion doesn't have de. It's on the frequency list that I got from Helma as de2 at 30. And I have it in the spreadhseet as de2. Do I need to do something different in the spreadsheet?

tyrannus is on the logeion frequency list ranked 941.

**Comment by jtauber** [comment]
`logeion-latin.txt` in the repo, which is what we're loading, doesn't have tyrannus but it does have de2. I'm going to see about handing the `2` in Logeion which might also address #160. It might be worth me looking at the frequency list you have to see if anything else is missing.

**Comment by IvyJL** [comment]
Regarding tyrannus, it does seem to be in the Logeion file called latininfo.db (@jtauber, previously shared with you on Google Drive). Not sure how that db file is related to logeion-latin.txt.
![Screen Shot 2020-10-22 at 10 30 56 AM](https://user-images.githubusercontent.com/18600875/96887666-cdf21400-1452-11eb-8db7-b5e6b9e7123d.png)

**Comment by jtauber** [comment]
#282 can be used to effectively solve this although doing further work so the wonky words list doesn't have to include both macron and non-macron versions of each form

**Comment by jtauber** [comment]
well, I should clarify: it effectively solves the cases where morpheus wasn't lemmatizing it. It doesn't solve tyrannus or de not being in the lattice but the solution there is to add them to lattice.

**Comment by jtauber** [comment]
The *lemmatization* problem is fixed though, so going to make a PR for #282 which will cover this too.

**Comment by IvyJL** [comment]
Hi, James,

Here’s the frequency list that I’ve been working with.

Best,
Ivy

**Comment by jtauber** [comment]
@IvyJL sorry, I think the attachment got dropped due to emailing GitHub. Can you send it to jtauber@eldarion.com ?

**Comment by IvyJL** [comment]
I've added some more words to the Wonky Word spreadsheet. The first two passages I tested showed up several more common things that were not lemmatizing properly in Morpheus.

**Comment by IvyJL** [comment]
@jtauber, I added the words discussed on 2021-04-08 to the Wonky Word spreadsheet at https://www.icloud.com/numbers/0Uhu4HMs6mXU7_b8P2I9RyMmA#Wonky_words_for_Hedera

**Comment by bilbe** [comment]
Done.
