### ISSUE TITLE
cannot set familiarity on some words

### ISSUE THREAD

**Issue by IvyJL** [Hedera-Lang-Learn/hedera#136]
in, plus, atque, de

I think these are all words that have been split into multiple entries in the spreadsheet vs one morpheus lemma

**Comment by bilbe** [comment]
https://dev.hederaproject.org/lemmatized_text/77/learner/

![image](https://user-images.githubusercontent.com/5712116/71187207-9ae85e00-224c-11ea-9d8c-0d91969004bc.png)

![image](https://user-images.githubusercontent.com/5712116/71187227-a5a2f300-224c-11ea-9930-6412b87683df.png)

**Comment by bilbe** [comment]
![image](https://user-images.githubusercontent.com/5712116/71187312-d84ceb80-224c-11ea-977b-ddc450ab47fb.png)

![image](https://user-images.githubusercontent.com/5712116/71187340-e438ad80-224c-11ea-9d4e-6a7173e73f8e.png)

**Comment by bilbe** [comment]
This is completely broken now. It doesn't work for any works

**Comment by IvyJL** [comment]
I’m on dev now and I noticed that the words that as a Learner I cannot set a familiarity level on are also words that are missing from the glosses list.
![78725EA3-2941-4F98-8BAB-4B1DD8B4204C](https://user-images.githubusercontent.com/18600875/71648749-54781200-2cd6-11ea-94e2-4cffe8c35304.jpeg)
![A08F840E-6444-47B5-A59B-E93ECAA98E73](https://user-images.githubusercontent.com/18600875/71648750-5510a880-2cd6-11ea-8efc-f75973a894de.jpeg)

**Comment by jtauber** [comment]
This should now be fixed on dev (branch) with 430a1d624f38a36cf5406d782fae95cf473daa02 (familiarity setting) and e88b2307a9635bb40bbd77b4a5fe38f5a284d5ce (glosses)

**Comment by jtauber** [comment]
Can this be closed?

**Comment by IvyJL** [comment]
Actually I need to go identify some specific words, but I thought that some words had dots, but they couldn’t be selected.
