### ISSUE TITLE
three types of list: set lists, teacher lists, personal lists

### ISSUE THREAD

**Issue by bilbe** [Hedera-Lang-Learn/hedera#145]
There need to be three types of lists:

1. set lists: Shelmerdine or any text book, i.e., unchangeable & public
2. teacher lists: words for 1st year, 2nd year, etc. public and private within classes
3. personal lists: my words that are ranked, shared with teacher

**Comment by jtauber** [comment]
We have the modelling done for this

1 = VocabularyList with NULL owner
2 = VocabularyList with teacher
3 = PersonalVocabularyList

We'd need to discuss what UX changes are desired.

**Comment by jtauber** [comment]
* vocabulary list drop down should only show the teacher's own lists plus the system ones
* check you can't delete other people's vocabulary lists
* visually indicate which are system ones
* include personal vocabulary in the drop down

**Comment by paltman** [comment]
Should there be explicit permission granted to share list with teacher?  If so, is it all or none, or can you check what entries you want to share (e.g. share a filtered list)?

**Comment by IvyJL** [comment]
Wow, I hadn’t even thought about sharing a filtered list, but that seems like a good idea.
Perhaps all by default (for simplicity for younger students), but some subtle option to filter?
Do you have thoughts, @bilbe?

**Comment by paltman** [comment]
@jtauber mentions both:

> vocabulary list drop down should only show the teacher's own lists plus the system ones

and 

> include personal vocabulary in the drop down

James, did you mean that the drop down should include all three: Teacher's Own Lists, System Lists, and Personal Lists?  

This makes sense to me but wanted to make sure.  @IvyJL thoughts?

**Comment by IvyJL** [comment]
Yes, please, all three kinds of lists.

**Comment by paltman** [comment]
are the personal lists that are added to the list, the personal lists of all the students that are in the class so you can click on say "Patrick Altman's Latin" and see my coverage for a text in the class?

**Comment by IvyJL** [comment]
If we’re talking about a class, yes, it would be ideal to see each student’s individual coverage and (perhaps down the line) an average for the all the class members.

**Comment by paltman** [comment]
is there any other reason to show personal vocab lists in this UI?

<img width="400" alt="Screen Shot 2020-09-25 at 10 11 16 AM" src="https://user-images.githubusercontent.com/1192/94292119-269cc280-ff22-11ea-9db9-36e665ee5a3f.png">

I think for the "how are my students and class doing" view, we can make a new view of that under the class room interface, maybe under the class list with a summary % view next to each student with a "drill in" view when you click on a student to see the text highlighted with details.

**Comment by IvyJL** [comment]
That alternative view sounds great. As for as the dropdown goes, let’s have system lists, teacher lists, and the teacher’s own personal list (some of us are still learning languages that we teach).

**Comment by paltman** [comment]
You got it!

**Comment by bilbe** [comment]
I was just thinking that if you are looking at a text in the context of the class. I would be hugely useful if you could choose some sort of aggregated list of the students, e.g., based on say... the common vocabulary of the students within the standard deviation, so we ignore the outliers both ends of the bell curve. 
![image](https://user-images.githubusercontent.com/5712116/94297950-5607fb00-ff33-11ea-9e05-ed96e7172811.png)


What do you think of that?

**Comment by IvyJL** [comment]
Uh, I might need some help on the notion of standard deviation. Perhaps we can talk about this next week, @bilbe ?

**Comment by bilbe** [comment]
Yeah, I was wondering how good your stats background was. I was hoping putting in the image would help. We can talk about it next week.

**Comment by paltman** [comment]
I now know `et`. ;)

<img width="1156" alt="Screen Shot 2020-09-25 at 12 41 21 PM" src="https://user-images.githubusercontent.com/1192/94298910-80a28580-ff2c-11ea-90f1-fb484a5ef9ea.png">

**Comment by IvyJL** [comment]
But look how much that gets you!

**Comment by paltman** [comment]
🎊

**Comment by paltman** [comment]
I think we should start a new issue for "Class stats" to capture this discussion on showing useful feedback to the teacher in context of a class.
