### ISSUE TITLE
update to later version of Ivy's spreadsheet

### ISSUE THREAD

**Issue by bilbe** [Hedera-Lang-Learn/hedera#148]
update to later version of Ivy's spreadsheet

**Comment by jtauber** [comment]
@IvyJL when I went to iCloud it wouldn't let me access your latest. Can you share again or email it to me?

**Comment by IvyJL** [comment]
https://www.icloud.com/numbers/0WPaTpU4CUXx5uiI7JcIYN8bg#DCC_Morpheus_for_Hedera

**Comment by IvyJL** [comment]
Weird. Please try this

https://www.icloud.com/numbers/0WPaTpU4CUXx5uiI7JcIYN8bg#DCC_Morpheus_for_Hedera

**Comment by IvyJL** [comment]
https://www.icloud.com/numbers/0WPaTpU4CUXx5uiI7JcIYN8bg#DCC_Morpheus_for_Hedera

**Comment by jtauber** [comment]
How many rows should I load in? Previously we only had ~265. The second sheet on the spreadsheet now has over 1000 lines but many are missing certain fields. Any suggestions on where to stop?

**Comment by jtauber** [comment]
I included 627 rows but ignored any that lacked a sub lemma or short def.

This is now pushed to dev in 7ede701
