### ISSUE TITLE
webpack dev server not working for fresh install

### ISSUE THREAD

**Issue by dodget** [Hedera-Lang-Learn/hedera#151]
In order to get the static files working locally on a fresh install, I had to change the output `publicPath` to `http://localhost:8000/static/`, and then run `npm run build`. There are mysterious issues with the webpack-dev-server.

This observation came from following the installation instructions.

**Comment by paltman** [comment]
I cannot reproduce this.  In addition, we use this same config on dozens of sites and this is the first I've heard of something like this happening.  This makes me thing there is something environmental going on that isn't obvious.  Can you describe your environment a bit?

**Comment by jtauber** [comment]
I just did a fresh install and had no problems.

**Comment by dodget** [comment]
Interesting! My colleague had the same issue that I did.

My environment - macOS Mojave, Python3, node v11.9.0, npm 6.5.0 postgres 11

Steps I use to install Hedera - 
```
# first terminal
$ redis-server
# ---
# second terminal
$ cd <hedera repo location>
$ nvm use 11.9.0
$ npm install
$ pipenv install
$ pipenv shell
(env)$ createdb hedera
(env)$ ./manage.py migrate
(env)$ ./manage.py loaddata sites
(env)$ ./manage.py shell -c "import load_ivy_lattice"
(env)$ ./manage.py shell -c "import logeion_load"
(env)$ export RQ_ASYNC=1
(env)$ ./manage.py runserver
# ---
# third terminal
$ cd <hedera repo location>
$ pipenv shell
(env)$ export RQ_ASYNC=1
(env)$ ./manage.py rqworker ${RQ_QUEUES:-default}
# ---
# fourth terminal
$ cd <hedera repo location>
$ npm start
```
For myself and my colleague, that leads to a functioning django project with no static files being served. Thanks, and please let me know if I can make anything clearer.

**Comment by dodget** [comment]
@joshuagetega found a workaround. Closing.
