### ISSUE TITLE
Familiarity set in personal word list does carry over to Learner reading environment 

### ISSUE THREAD

**Issue by IvyJL** [Hedera-Lang-Learn/hedera#156]
Words imported into personal word list get a default familiarity, but the familiarity doesn’t carry over to the Learner Reading mode. I tried changing familiarity in the personal word list and still nothing. (But words that enter the personal word list from the Reading mode do still work). 
![57565C66-A358-4C6A-AE30-9A622E731F7C](https://user-images.githubusercontent.com/18600875/71700077-9e253300-2d90-11ea-93ba-f53a741dd23c.jpeg)
![7EE69457-F0F9-44D5-90DB-34386D5BE22E](https://user-images.githubusercontent.com/18600875/71700078-9e253300-2d90-11ea-8d21-3483d7adc703.jpeg)

**Comment by jtauber** [comment]
Is this an issue? It may have been fixed by our last round of fixes.

**Comment by IvyJL** [comment]
I think this has been fixed. I’m closing it.
