### ISSUE TITLE
Lemmatizing of hic

### ISSUE THREAD

**Issue by IvyJL** [Hedera-Lang-Learn/hedera#160]
![33F36566-9623-4FBA-8BA1-2323358C3885](https://user-images.githubusercontent.com/18600875/72205736-7864f180-3454-11ea-8a5f-ecb566fbf946.jpeg)
Latin _hic_ only lemmatized as hic “this”, but should offer choice between _hic_ “this” and _hic_ “here”

“here” is technically hīc with a long i but that shouldn’t matter

**Comment by jtauber** [comment]
Is this in your spreadsheet?

**Comment by IvyJL** [comment]
Yes, they are. hic “this” is morpheus hic1 and hīc “here” is morpheus hic2. 
But I suppose this might be the same issue as ignoring macrons actually.

**Comment by IvyJL** [comment]
I think this issue is bigger than just hic vs hīc. Right now most words with macrons are not being found at all.

**Comment by jtauber** [comment]
There are two problems here. One is that Morpheus only lemmatizes hic as (effectively) hic1 and secondly that Morpheus doesn't lemmatize hīc at all. Working on a fix for at least the latter by stripping macrons before calls to Morpheus but that won't fix the original issue.

**Comment by jtauber** [comment]
On a branch, I've fixed the second probably by always stripping macrons before calling Morpheus for Latin.

**Comment by jtauber** [comment]
The root of the first problem seems to be that Logeion's hic2 is never linked under hic. I'm investigating whether it's worth always linking a Logeion lemma with a number to a parent node without the number.

**Comment by jtauber** [comment]
The hic-specific problem could be solved in the lattice spreadsheet but if it is going to occur with many words where Morpheus doesn't know one of the senses but Logeion does then we can solve it in the Logeion load.

**Comment by jtauber** [comment]
I'm giving some thought as to whether this relates to #135 as well.

**Comment by IvyJL** [comment]
Not sure how often this type of problem will occur, but if we could at least fix it for very common words, that would be great. Both hic’s are very common.
