### ISSUE TITLE
Gloss in Learner Mode

### ISSUE THREAD

**Issue by bilbe** [Hedera-Lang-Learn/hedera#165]
There used to be a revealable gloss in the Learner moved with the Toggle off. I think it was sort of a hint for the reader. Did we do away with this intentionally? or should we put it back?

**Comment by paltman** [comment]
@bilbe I believe it's still there but the vocabulary entries are not populated for the LatticeNode for some reason.  This might be related to what @jtauber is working on or might be some other data issue.
