### ISSUE TITLE
Unresponsive vocab list dropdown

### ISSUE THREAD

**Issue by joshuagetega** [Hedera-Lang-Learn/hedera#174]
When you click to select a vocab list in the vocab list dropdown, the browser page freezes. All buttons become unclickable. After some time, the browser displays a message that the page is unresponsive.

**Comment by IvyJL** [comment]
@joshuagetega I'm not seeing this issue now. Do you want to double-check and close if OK now?

**Comment by joshuagetega** [comment]
@IvyJL, yes, I'll go ahead and close it. I found the cause of the issue and fixed it a few weeks back.

**Comment by joshuagetega** [comment]
Issue is no longer valid.
