### ISSUE TITLE
Add Lemma node information to alt/hover text

### ISSUE THREAD

**Issue by bilbe** [Hedera-Lang-Learn/hedera#193]
The lemma node is displayed in the interface in a number of places. This is really just for debugging and so I'd like to recommend that it be kept, but stuck in hover/alt text. That way it can still be used. Perhaps it could be configurable so that we can have it displayed in dev environments and not in production.

It would just make this a bit more polished.

**Comment by IvyJL** [comment]
Agreed it would be nice to have the node info in dev but not prod, if that's no too complicated. I'd be concerned about having it on hover since hover might be used for other things.

**Comment by paltman** [comment]
Are we talking about the lattice node id like in this picture?  e.g. 13, 11, 12, 14, and 15?

<img width="288" alt="Screen Shot 2020-08-26 at 4 32 59 PM" src="https://user-images.githubusercontent.com/1192/91359243-cfd48980-e7b9-11ea-81ad-536738515c69.png">

**Comment by jtauber** [comment]
If not hover, we could do it as a toggle or even a user setting.

My concern with prod vs dev is then we have no way of testing its absence before prod.

**Comment by paltman** [comment]
![Screen Recording 2020-08-27 at 07 51 55 AM](https://user-images.githubusercontent.com/1192/91444448-5e88eb00-e83a-11ea-9603-3dfdf7eb9363.gif)

**Comment by paltman** [comment]
Add the ability to have a user setting that defaults to `Off`, but you also set to `Always On` or `Toggle On or Off`
