### ISSUE TITLE
Gloss export in Student view should include rating

### ISSUE THREAD

**Issue by bilbe** [Hedera-Lang-Learn/hedera#206]
Ivy, Steven Clancy, and I had a discussion about including the user's rating along with the word and definition in the CSV file that is exported. I'm assuming/hoping this won't be too difficult.

**Comment by paltman** [comment]
The current glosses list (and export) only list the unknown ones.  That means that the ratings will all be blank.  Does this mean we should change that filtering so either/both the display list of glosses and/or the export don't filter to just the unknowns? @bilbe

**Comment by jtauber** [comment]
seems like what's really being asked for here is a way to export the Personal Vocabulary List, not text-specific unknown words.

Can I propose we keep the ability to download the unknown words for a particular text and ADD the ability to export one's full personal vocabulary list with ratings from the personal vocabulary page.

**Comment by IvyJL** [comment]
Yes, keeping the “export unknown for a particular text” and adding “export personal list with ratings” sounds good.
