### ISSUE TITLE
Odd behavior with "res"

### ISSUE THREAD

**Issue by bilbe** [Hedera-Lang-Learn/hedera#209]
So if you parse the Prologue of Livy's Ad Urbe Condita, it doesn't even offer the definition of "res" as the "things"

![image](https://user-images.githubusercontent.com/5712116/86273583-82171880-bb9e-11ea-8a42-0818cf8d2f29.png)

Here is the text:

Facturusne operae pretium sim si a primordio urbis res populi Romani
perscripserim nec satis scio nec, si sciam, dicere ausim, quippe qui cum
veterem tum volgatam esse rem videam, dum novi semper scriptores aut in
rebus certius aliquid allaturos se aut scribendi arte rudem vetustatem
superaturos credunt. Utcumque erit, iuvabit tamen rerum gestarum
memoriae principis terrarum populi pro virili parte et ipsum consuluisse; et
si in tanta scriptorum turba mea fama in obscuro sit, nobilitate ac
magnitudine eorum me qui nomini officient meo consoler.

**Comment by jtauber** [comment]
Okay that does seem odd. I just checked Morpheus and it returns "reor" and "res" as the ambiguity as reflected in the label for node 883832. Let me try with a clean install locally to make it sure it's not some weird stale data issue.

**Comment by jtauber** [comment]
It's definitely bad data as a clean install results in:

<img width="406" alt="Screen Shot 2020-07-02 at 10 40 41 PM" src="https://user-images.githubusercontent.com/24426/86372719-28edd880-bcb5-11ea-9711-4d0283e6dbf8.png">

**Comment by jtauber** [comment]
Was this on dev or production? I wonder if we just haven't updated it for a while.

**Comment by IvyJL** [comment]
Just tried and both dev and prob have the problem.

**Comment by jtauber** [comment]
My bet is we have databases from a while ago before my last round of lattice-building fixes although I'll continue to investigate.

**Comment by jtauber** [comment]
Do we know the last time the databases were rebuilt?

**Comment by IvyJL** [comment]
Working properly on dev and prod as of 2020-07-31. Closing.
