### ISSUE TITLE
Stundent link to text not working in dev or prod

### ISSUE THREAD

**Issue by bilbe** [Hedera-Lang-Learn/hedera#222]
So I added a student version of me to prod and became a student in a course, but can't access the one text there. You can join the class with this link:

https://hederaproject.org/classes/88e35e57-a24f-4f7a-a73f-74248288c9d9/join/

I get a Page Not Found error.

**Comment by paltman** [comment]
This is fixed already just hasn't merged yet in #220

**Comment by paltman** [comment]
I don't think we've ever established a formal review process so I'm not sure if I should just merge when a PR I've created is ready or if it should be peer reviewed and accepted first.
