### ISSUE TITLE
implement batch lemma disambiguation

### ISSUE THREAD

**Issue by jtauber** [Hedera-Lang-Learn/hedera#23]
sometimes a text will have a lot of cases of an ambiguous A that could be lemmatised B or C but you want to be able to say "in this text, all A are to be lemmatised as B not C"

**Comment by jtauber** [comment]
We need to decide what the UX is like for this. Do you shift-click on the lemma or something?

**Comment by IvyJL** [comment]
Would shift-click be problematic for mobile?

**Comment by jtauber** [comment]
1) automatically mark as resolve when node selected
2) separate button for "apply all" (once you've disambiguated one)

**Comment by jtauber** [comment]
note on 3: only apply to other tokens of same form if that other token is unresolved
