### ISSUE TITLE
RFC: Eliminate lattice backward crawl

### ISSUE THREAD

**Issue by IvyJL** [Hedera-Lang-Learn/hedera#253]
When disambiguating something like est, we have two options (sum & edo), but after choosing sum, we see more ambiguities from other forms of sum.

![Screen Shot 2020-09-18 at 2 00 30 PM](https://user-images.githubusercontent.com/18600875/93630076-61997600-f9b7-11ea-9523-0aaa0a33c6bb.png)

**Comment by jtauber** [comment]
Also see *amas* in #144 comment

**Comment by IvyJL** [comment]
I think this is what I'd like to see: for a word like _est_, at first just the two headwords _sum_ and _edo_ are shown as disambiguation choices (no "morpheus ambiguity" umbrella node). When I click the headword _sum_ as the correct one in this situation, the other headword (_edo_) should no longer be visible. But there should be some indicator that _est_ was ambiguous and some way to reshow the original choice of headwords.

Tylor mentioned that if a click on a headword disambiguates, then a click on the same headword should undo that (i.e. I click _sum_ to disambiguate betweem _sum_ and _edo_ and I click _sum_ again to go back to the choice of _sum_ and _edo_). This seems very sensible. 

But I think after a disambiguation choice is made and the user has clicked, then there needs to be some indicator that there are actually choices to go back to. So if, for example, someone else goes to review the disambiguation choices that have been made, they should be able to see what words were disambiguated so that they can reveal the choices again and change if necessary.

**Comment by bilbe** [comment]
No longer an issue
