### ISSUE TITLE
Texts multiply like rabbits

### ISSUE THREAD

**Issue by bilbe** [Hedera-Lang-Learn/hedera#254]
Every time you add a text to a class, it makes a copy AND it is not longer disambiguated.

Teacher should have a choice of whether to just add the text to the class or clone it.

**Comment by bilbe** [comment]
When a teacher takes a text from our library, it stays connected and they get correction. If they edit it, then it's theirs.

**Comment by paltman** [comment]
@bilbe @jtauber guessing this is kind of a dupe with #243 

I'll put #243 in progress as I think that is what will fix this.
