### ISSUE TITLE
Personal list not calculating anything when selecting in dropdown.

### ISSUE THREAD

**Issue by paltman** [Hedera-Lang-Learn/hedera#264]

**Comment by paltman** [comment]
@IvyJL This is working for me.  I wonder what is different about our environments or maybe we are not looking at the same thing.

<img width="905" alt="Screen Shot 2020-10-08 at 2 24 12 PM" src="https://user-images.githubusercontent.com/1192/95504330-3da3d180-0972-11eb-9ff1-21717d0eb1e7.png">

<img width="1198" alt="Screen Shot 2020-10-08 at 2 24 30 PM" src="https://user-images.githubusercontent.com/1192/95504334-3f6d9500-0972-11eb-9250-6540bf12cd02.png">

**Comment by IvyJL** [comment]
Hmm. I'm on the dev site. I added the same tsv file as my personal list and then again as a "teacher list". I get a percentage when I select it as one of my teacher lists, but not when I select it as my personal list. Does the personal list only work if I'm looking at it as a student?

**Comment by paltman** [comment]
@IvyJL after you imported did you set different familiarity for each word?

**Comment by IvyJL** [comment]
On importing, I choose to set everything at 3. Later I changed some to 5. It didn’t seem to make a difference.

**Comment by paltman** [comment]
ok, @IvyJL, I've figured out what's going on and why you were seeing it and I was.  marking familiarity as a learner, you have the selected node in context and therefore can link it to the vocab entry.  on the personal vocab list we don't have any lemma nodes to link to so it's never set when we set familiarity.  

it's obvious now that we need to bridge that gap somehow for it to be useful in importing and ranking your words on the vocab list page.  I need to think that through a bit.

**Comment by IvyJL** [comment]
I think I get it. So I uploaded the same TSV file to be my personal list and also as a teacher list. When I select it as a teacher list, it shows me percentages, but when I select my personal list, it doesn’t. So it’s getting lemma nodes one way, but not the other?

**Comment by bilbe** [comment]
I think this is working, but look at issue 267. I think this explains what Ivy is seeing.
