### ISSUE TITLE
Words like mea (my) list three versions of the same gloss when disambiguating 

### ISSUE THREAD

**Issue by bilbe** [Hedera-Lang-Learn/hedera#268]
The title says it all. Maybe Ivy can add a text to test.

**Comment by IvyJL** [comment]
You can just put in "vivamus, mea puella, atque amemus"
The attached image shows the multiple versions.

![Screen Shot 2020-10-14 at 3 15 57 PM](https://user-images.githubusercontent.com/18600875/96046964-557fc780-0e42-11eb-8801-80af9331de1e.png)

**Comment by jtauber** [comment]
Note the screenshot above is of the learner mode, not the teacher / disambiguation mode.

Not denying the bug, just trying to narrow it down.

There are indeed three readings of "mea" according to the lemmatizer: the possessive adjective, the verb (meo), and the noun meum (a type of plant, apparently). 

<img width="378" alt="Screen Shot 2020-10-22 at 5 58 44 PM" src="https://user-images.githubusercontent.com/24426/96856596-a9b52800-1490-11eb-8196-2459db1caebc.png">

I presume from Ivy's screenshot that mea had been correctly disambiguated as it's not bold.

I'll try to reproduce this problem in learner mode myself but just wanted to provide the above data so far.

**Comment by jtauber** [comment]
With a fresh install, this is what I see.

If I have NOT disambiguated, the learner mode looks like this:

<img width="380" alt="Screen Shot 2020-10-22 at 6 04 47 PM" src="https://user-images.githubusercontent.com/24426/96857274-60190d00-1491-11eb-870d-d5a0309a519f.png">

whereas if I HAVE disambiguated, it looks like this

<img width="376" alt="Screen Shot 2020-10-22 at 6 06 14 PM" src="https://user-images.githubusercontent.com/24426/96857318-6dce9280-1491-11eb-9747-063f7a8f12e1.png">

So I think we'll need to investigate the data on the server as clearly it's working fine with a clean install.

**Comment by jtauber** [comment]
I'm confused now as I can't get my screenshot to look like yours Ivy. Perhaps we can discuss on the call today.

**Comment by IvyJL** [comment]
Cool! That looks like what we want.

**Comment by jtauber** [comment]
show vocab list in parentheses
