### ISSUE TITLE
Error uploading new vocab tsv lists

### ISSUE THREAD

**Issue by IvyJL** [Hedera-Lang-Learn/hedera#280]
I'm getting a"something went wrong message" when trying to upload a tsv file as a new vocab list. Both dev and prod. Not sure if it's because the new lattice isn't in place yet.
Any hope of fixing this by Monday 2020-11-16? It's kind of critical to the Wednesday presentation.
@paltman @jtauber

**Comment by paltman** [comment]
I'll investigate mañana. 

I'd love it if we could get Sentry added back otherwise we will continue to fly blind on operational issues that come up.

**Comment by IvyJL** [comment]
Thanks, Patrick!

**Comment by paltman** [comment]
I should have asked for this last night but can you send me the TSV file you were using?

**Comment by paltman** [comment]
I wonder if your TSV had duplicates?  I can see where it errors out where there is a duplicate headword.

This small sample works for me locally.


| head | gloss |
| -------------- | --------------- |
| sum, esse, fuī | to be, exist, live |
| et | and |
| quī, quae, quod | who, which, what |

**Comment by IvyJL** [comment]
Sure. I’ll try something smaller too.

**Comment by IvyJL** [comment]
OK, I think it’s something wrong with my files. I just got a 3-item tsv imported to prod.
Anything in particular I should be looking for?

**Comment by paltman** [comment]
Any headwords without a gloss?
Any duplicated headwords?

Both of those will cause an exception.  Eventually we should just show you everything that you uploaded in a table on the website with red flags on the issues with options to ignore or the abiliy to edit/correct, before clicking a final button to ingest.

**Comment by IvyJL** [comment]
Yep, duplicate headwords.
