### ISSUE TITLE
List of wonky words not in Morpheus

### ISSUE THREAD

**Issue by IvyJL** [Hedera-Lang-Learn/hedera#282]
We need a way to handle words that Morpheus doesn't recognize. Like tyrannus, salio, etc.
Ivy's goes to make a two-column list of forms/lemmas. #135

**Comment by jtauber** [comment]
Loading these into the FormToLemma table with

```
./manage.py shell -c "from lemmatization.models import FormToLemma; FormToLemma.load_tab_delimited(open('import-data/ivy_extra_latin_forms.tsv'), '', 'lat')"
```

solves the problem although I'm just working on the macron issue.

**Comment by bilbe** [comment]
No longer a problem
