### ISSUE TITLE
As a student I want to be able to mark words from a Chinese text to my personal word list

### ISSUE THREAD

**Issue by elliottyates** [Hedera-Lang-Learn/hedera#304]

**Comment by elliottyates** [comment]
@bilbe -- can we clarify this? Is this a new function (for all languages) that means a student can select a lemma in the text view and add it to the personal vocab list right there? (I believe this doesn't exist.) Or is it, rather, feature parity with other languages -- that a Chinese-language personal vocab list will, in fact, work with Chinese texts? (I'm thinking it's the latter, right?)

Thanks!

**Comment by bilbe** [comment]
In both cases, I think that should just work with Hedera the way it is. If you click on a word when reading a text and say that you know it well (i.e., click on one of the dots or use 1-5 on the keyboard), then it automatically gets added to your personal list AND that should feed back to the text so all instances of that word should now indicate that you know it to that degree. I'm not away of anything special that needs to be done, but you might want to ask @arthurian

**Comment by elliottyates** [comment]
@bilbe thanks -- got it. :) I didn't know that it worked that way, I'll test that!

**Comment by elliottyates** [comment]
Confirmed this is working.
