### ISSUE TITLE
As a a teacher, I want to be able to compare a Chinese text to a common word list (e.g. HSK)

### ISSUE THREAD

**Issue by elliottyates** [Hedera-Lang-Learn/hedera#306]

**Comment by elliottyates** [comment]
@bilbe can we clarify this -- is it the ability to import shared Chinese words lists like the HSK, or it is actually including HSK word lists in the service?

**Comment by bilbe** [comment]
Again this is a feature built in. Once you have a word list that either you have uploaded (for a class) or there is a universally available word list, then you can select it when you are adding and disambiguating texts. We should probably make the HSK part of the initial load. What do you think @IvyJL? NB, @dodget.

**Comment by elliottyates** [comment]
We agreed this was complete, general Chinese parser/lemmatizer bugs notwithstanding (see [Bill's doc](https://docs.google.com/document/d/11o-13f9I23hFV0agUKvSVd2iXV4eUKthD2KAx_1ZMCM/edit)), on our Chinese testing Zoom call Dec 13, 2021, so moving this to Done.
