### ISSUE TITLE
As a user, I'd like to be able to clone texts so that the lemmatization is preserved

### ISSUE THREAD

**Issue by arthurian** [Hedera-Lang-Learn/hedera#308]
Ability to copy the text + lemmatization (currently just copies the text, losing the hard-work of disambiguating the text).
Perhaps all copies should be like point a, but then we need a mechanism for editing the text that doesn’t lose lemmatization. (e.g., substitute: interficio for occido)

**Comment by arthurian** [comment]
Acceptance Criteria
- Cloned text should retain the lemmatization

**Comment by bilbe** [comment]
Copy the lemmatized form of the text and don't go to the lemmatization process
