### ISSUE TITLE
Personal vocab lemma link

### ISSUE THREAD

**Issue by arthurian** [Hedera-Lang-Learn/hedera#322]
On the personal vocabulary page, the **Lemma Link** should be displayed (like the main vocab), and the user should be allowed to change that.

Note: discussed this after the demo of the dashboard _Quick Add Vocab_ on 7/8/21.

**Comment by IvyJL** [comment]
In dev now, the Lemma is visible in the Personal Vocabulary, but editing lemmas does not work completely.
I can change a lemma once, but if I try to change it again, the change doesn’t stick.

**Comment by IvyJL** [comment]
Actually, multiple changes do stick, but the problem is editing to a lemma that includes a number (like hic2). It will go in as just hic and lose the number.

**Comment by bilbe** [comment]
No longer an issue
