### ISSUE TITLE
RFC: Morpheus data service

### ISSUE THREAD

**Issue by arthurian** [Hedera-Lang-Learn/hedera#350]
While a specific proposal is being made in this RFC, it is subject to change based on the discussion and feedback. The goal is to have consensus on the right approach.

## Summary

This is a proposal to improve Hedera's lemmatization of latin texts by implementing our own headword/lemma retrieval service rather than calling out to Morpheus via the [Perseids Morphology Service API](http://services.perseids.org/). This approach is feasible because we have a copy of the underlying data for Morpheus.

## Motivation

Two common spelling variations occur in Latin having to do with i/j and u/v. It is common to distinguish between u/v, but not i/j. Morpheus will often recognize the same word spelled differently (though not always, as shown below), but even when it's recognized, it's difficult to predict the spelling that will be used.

Examples:
- [iacio](http://services.perseids.org/bsp/morphologyservice/analysis/word?engine=morpheuslat&lang=lat&word=iacio), [jacio](http://services.perseids.org/bsp/morphologyservice/analysis/word?engine=morpheuslat&lang=lat&word=jacio) → `jacio`
- [iuvo](http://services.perseids.org/bsp/morphologyservice/analysis/word?engine=morpheuslat&lang=lat&word=iuvo), [juvo](http://services.perseids.org/bsp/morphologyservice/analysis/word?engine=morpheuslat&lang=lat&word=juvo) → `juvo`
- [iam](http://services.perseids.org/bsp/morphologyservice/analysis/word?engine=morpheuslat&lang=lat&word=iam), [jam](http://services.perseids.org/bsp/morphologyservice/analysis/word?engine=morpheuslat&lang=lat&word=jam) → `iam`
- [adiudicare](http://services.perseids.org/bsp/morphologyservice/analysis/word?engine=morpheuslat&lang=lat&word=adiudicare), [adjudicare](http://services.perseids.org/bsp/morphologyservice/analysis/word?engine=morpheuslat&lang=lat&word=adjudicare) → `adjudico`, [adivdicare](http://services.perseids.org/bsp/morphologyservice/analysis/word?engine=morpheuslat&lang=lat&word=jacio) → _None_
- [nuntius](http://services.perseids.org/bsp/morphologyservice/analysis/word?engine=morpheuslat&lang=lat&word=nuntius) → `nuntius` [nuncius](http://services.perseids.org/bsp/morphologyservice/analysis/word?engine=morpheuslat&lang=lat&word=nuncius) → _None_

This inconsistency can cause issues when Hedera tries to link the retrieved lemma to a definition in [Logeion](https://logeion.uchicago.edu/) (an open-source dictionary for Latin and Greek) or a node in the lattice structure that has been curated with specific glosses and meanings.

## Original Proposal

_Note: skip ahead to the Updated Proposal as this has been revised and left here for reference._

The proposed approach is to split out a new Django app to own the Morpheus data and handle the logic for querying and resolving spelling issues.

1. Create new django app: `lemmatization.latin`.
2. Create models: `lemmatization.latin.models`.
    - Perform a one-time import of the `LatinMorph16.db` data.
    - Generate a DB dump that can be used to quickly load the table(s) thereafter.
3. Move `MorpheusService` into `lemmatization.latin.services`.

This structure achieves a modest degree of isolation from the lattice and lemmatization cache without adding too much complexity. The `lemmatization.FormToLemma` model can continue to be used as a cache when looking up new words and to maintain a mapping of wonky words. It also does not require any significant changes to how it will be consumed. It could just as easily be provided as a separate API.

The `MorpheusService` would be able to immediately apply i/j spelling rules to ensure that all j's are changed to i's. Logeion dictionary entries loaded into the database would need to be checked to ensure that they follow the same rule.

Additional improvements to querying and data representation could be implemented after careful analysis (e.g. looking at the Logeion data and Ivy's lattice).

## Updated Proposal

The updated approach is to create an immutable model in `lemmatization.models` that can be queried directly by `MorpheusService` from `lemmatization.services`.

More broadly, the concept is to add language-specific models to the `lemmatization` django app whenever a particular language does not have a lemmatization API that can be used (e.g. Chinese), or would benefit from more robust lemmatization by querying the data directly as opposed to calling out to an API (e.g. Latin). 

Key points:
- **Abstract Base Class**. Add an ABC to `lemmatization.models` that provides a common interface for a language backend. Derived models will be considered read-only (e.g. users of these models should not call `save()`).
- **Language-specific Models**. Each supported language can optionally derive a model from the ABC, adding any fields that are needed, and the corresponding language service can query it from `lemmatization.services` when lemmatizing texts.
- **Data Loading**. Data will be loaded through SQL dumps since they are not expected to change after the initial load, and this will allow them to be loaded (or re-loaded) quickly. 

## Drawbacks

Hedera would not receive any updates made by the upstream Perseids Morphology Service. This could also be viewed as a positive, since there would also  be no surprises. That said, Morpheus is quite stable, for better or worse, so this doesn't seem like much of a concern.

## Alternatives

If we accept the premise that Hedera would benefit from managing its own headword retrieval service, there are two alternative implementations to consider:

1. Create a separate web service that wraps the Morpheus data and implements the required behavior for Hedera. The only difference from Hedera's point of view is that it's calling the new service API endpoint.
    - **Pros**: Complete isolation from Hedera and freedom to evolve independently. 
    - **Cons**: Yet another service to manage with the attendant infrastructure, and questions about whether it should be a public service or restricted to Hedera.
2. Import the Morpheus data directly into Hedera using the `lemmatization.FormToLemma` model to map forms to a lemmas, implementing the required spelling rules. This would short-circuit any requests to the real Perseids API.
    - **Pros**: Simple to implement.
    - **Cons**: Limited functionality and mixing of concerns. This model is intended as a cache of forms that have been lemmatized, not as a complete database mapping forms to lemmas. Also, it would likely be very slow to load ~400K forms. Updates could be complicated.

**Comment by dodget** [comment]
Thanks for putting this together @arthurian. I have two quick thoughts on the proposal:

### App Structure

Currently in Hedera, django apps exist at the level of the project root. Are you proposing that the new `lemmatization.latin` app be nested within the existing `lemmatization` app? I think the proposal makes sense semantically, but is that idiomatic django? Wouldn't that increase the cognitive load to grokking Hedera in the future? Like I said, I think that part of the proposal makes sense semantically, but maybe it should accompany a restructuring of Hedera's apps.


### Dual Nature of the Morpheus Service

Currently, the `MorpheusService` serves both latin and greek. If we moved the `MorpheusService` to `lemmatization.latin.services` one wouldn't think that is also the greek service.

**Comment by arthurian** [comment]
Thanks for the comments @dodget. I had forgotten about greek with respect to the `MorpheusService` (oops!). The data we received only covers latin, so I had been focused on that and was thinking along the lines of making the language and service relationship more explicit.

In terms of the app structure, while I like the namespacing benefits of nesting the app and closely associating it with lemmatization (not just a general app), I agree with your point about keeping a flat structure for now.

How about we elevate the morpheus module to an app at the project root level, adding `morpheus.models` and `morpheus.services`? The `MorpheusService` would be able to continue serving both latin (from the local data store) and greek (from the Perseids API) and the name should be immediately recognizable if you're familiar with the codebase at all. Thoughts?

**Comment by arthurian** [comment]
Note: @dodget @Tanvez and I discussed this a bit more offline, and have determined that the best path forward may be to eschew the additional django app and simply incorporate the new model into `lemmatization`.  I will go ahead and update the original proposal to that effect (keeping the original for reference).

**Comment by elliottyates** [comment]
This could also work for Chinese; I wonder if the base lemmatizer class could also support extension for calling out to APIs in the event that the local cached headword/gloss DB doesn't have something. Otherwise, I think that using models can subclass a basic standard could work fine. 👍

**Comment by arthurian** [comment]
Thanks all for the feedback. I'm going to go ahead and close this issue since the updated proposal has been accepted by the team.
