### ISSUE TITLE
M-Dashes in text created tokenization problems: Livy

### ISSUE THREAD

**Issue by bilbe** [Hedera-Lang-Learn/hedera#36]
Livy, Ab Urbe Condita
https://hederaproject.org/lemmatized_text/1/

When I added Livy's text, I copied and pasted from an online source. It contained m-dashes that created new words and unknown words, e.g., "est—Romularem". This is this something easily addressed in the tokenizer/pre-tokenizer?

**Comment by jtauber** [comment]
Yep, this will be easy to address. At the moment, we're naively splitting on whitespace but we can be a bit smarter about punctuation.

**Comment by jtauber** [comment]
For now, I've implemented a compromise where "foo—bar" gets tokenised into "foo—" and "bar" which then works correctly. The side-effect is you get the slightly ugly "foo— bar" displayed (with a space after but not before the em-dash) so we might want to consider ways of better handling punctuation in the tokenisation post-5/8.

**Comment by bilbe** [comment]
This is working just fine
