### ISSUE TITLE
Uploading Vocabulary List from spreadsheets is borked

### ISSUE THREAD

**Issue by bilbe** [Hedera-Lang-Learn/hedera#366]
We were given a demo Friday (10/1/2021) at 3:25pm and couldn't upload a vocabulary list.

**Comment by arthurian** [comment]
Main issue is that duplicates in the word list causes a failure.

**Comment by bilbe** [comment]
Example Lists: https://drive.google.com/drive/u/0/folders/10yXeIZ9mUMDYEHJjU5iibJFfIMaIxHvH

**Comment by arthurian** [comment]
This should be resolved by #396
