### ISSUE TITLE
I want to be able to edit a text that I've added

### ISSUE THREAD

**Issue by bilbe** [Hedera-Lang-Learn/hedera#37]
The title says it all. I want to be able to edit a text I've added because there were typos.

**Comment by jtauber** [comment]
That's what the clone is for.

**Comment by bilbe** [comment]
From a developers perspective, this makes perfect sense, but at some point we should just call it edit. I would also like to see an edit button on the reading page, if I own the text. I wanted to go in and add spaces around the m-dashes and it was immediately obvious.

**Comment by jtauber** [comment]
One of the reasons we discussed when originally going the current route was not changing stuff in texts already in use.  We should probably distinguish whether the text is in use or not. 

There is also the separate issue of losing any lemma disambiguation (that's a much harder problem to solve!)

**Comment by bilbe** [comment]
This is working for the most part. There are a couple little things, but I'm going to close this one.
