### ISSUE TITLE
We definitely need more word lists before we can demo on April 8

### ISSUE THREAD

**Issue by bilbe** [Hedera-Lang-Learn/hedera#38]
We definitely need something beside the DCC vocabulary list for Latin. This is not a pretty picture.

<img width="1173" alt="image" src="https://user-images.githubusercontent.com/5712116/54759465-85aea800-4bc4-11e9-9b2c-bc718f6cc33c.png">

**Comment by bilbe** [comment]
Here is an example of the problem here too, so some of this may be due to the default way the lattice is made.
<img width="1173" alt="image" src="https://user-images.githubusercontent.com/5712116/54759845-45035e80-4bc5-11e9-8505-5b8b9964bbe5.png">

**Comment by bilbe** [comment]
I've been resolving a bunch of these ambiguities. Ugh. We need some ways to automate/speed up this process.

**Comment by jtauber** [comment]
The server doesn't have the Logeion words loaded which will help (with definitions, etc).

We still need to add the batch disambiguation and probably need to brainstorm other UX ideas to speed up the disambiguation process.

**Comment by bilbe** [comment]
With regard to speeding things up, here is a perfect example:

<img width="410" alt="image" src="https://user-images.githubusercontent.com/5712116/54765701-5b62e780-4bd0-11e9-8f88-0221eb0f6924.png">

There is really only one answer to this. It should just choose "422. lemma speciēs"

**Comment by jtauber** [comment]
this should be fixed by #64
