### ISSUE TITLE
Catullus, e.g., will have some specialized vocabulary, that we may need to deal with

### ISSUE THREAD

**Issue by bilbe** [Hedera-Lang-Learn/hedera#39]
We may need to think about texts with adult content and vocabulary. My son reading is one of Catullus's less racy poems, but someone will add some of his other poems (it may be us) and we may need to worry about having middle school Catholic kids discovering them. Just saying.

**Comment by jtauber** [comment]
we could easily have a content rating attached to texts but not sure how to enforce "parental controls"
