### ISSUE TITLE
Misinterpretation of words ending in -ve when it is not enclitic

### ISSUE THREAD

**Issue by IvyJL** [Hedera-Lang-Learn/hedera#450]
The form _nave_ (_navis_ “ship” in the abl. sg.) is getting split as if with the enclitic _-ve_.

Also happening with _cive_ (_civis_ “citizen  in the abl. sg.), _salve_ (“hello”), and others. We need to convince Hedera that _salve_ is "hello" not "or salt" (for example).

Some others like _grave_ and _clave_ (from _gravis_ and _clavis_) were not associated with their lemmas at all. I associated them via Django.

I suspect these are related because the first half of _nave_, _salve_, and _cive_ are recognized as things that could exist independently, whereas _gra_- and _cla_- are not. So Hedera couldn't lemmatize them as anything after removing the erroneous enclitic.

**Comment by bilbe** [comment]
@IvyJL I think this is working now. Can you check?

**Comment by IvyJL** [comment]
Those words are working, but there are others (dive < divus, sive). Will they need to be addressed individually?

**Comment by bilbe** [comment]
So these are just going to have to be fixed as they come up... unless you have a list. I just added them to the form_to_lemma table. They seem to be working now.

**Comment by IvyJL** [comment]
I had started adding some on your [form-to-lemma Numbers file](https://www.icloud.com/numbers/0ca1k3zpxeFfpGUiJygzaDryw#Form_To_Lemma).

**Comment by bilbe** [comment]
I'll have a look.

**Comment by IvyJL** [comment]
I suspect we will have cases with -ve similar to the below:

I’ve also been making a bunch of form-to-lemma connections for ablative sg like harundine (> harundo) and foramine (> foramen).

But for words where the first part can be understood as a free-standing word, just making those connections isn’t enough.
So cupidine is still being understood as cupidi + ne and ordine as ordi + ne.
How are we dealing with those?

**Comment by bilbe** [comment]
Actually it should be. Are you reparsing the texts? Editing them doesn't seem to be enough. I just did cupidine and ordine in a new text and it worked fine. Try that.

**Comment by IvyJL** [comment]
Yes, reparsing worked. One thing I'll need to remember to document is cases like tenē (imperative of teneō) vs. tēne (acc/abl of tu + ne). If the latter, people will have to use a pipe.

**Comment by IvyJL** [comment]
That would be very cool, assuming we limit to just the cases where the first part really could be a form.
