### ISSUE TITLE
Lattice needs to filter on language

### ISSUE THREAD

**Issue by bilbe** [Hedera-Lang-Learn/hedera#46]
We've been playing around and discovering all sorts of interesting things. Here's one of my favorites:

![image](https://user-images.githubusercontent.com/5712116/55750301-f9e4aa80-5a10-11e9-99e4-c4f64af0834f.png)

Latin text with a Greek lemma!

Thought you should know.

**Comment by jtauber** [comment]
I'm pretty sure that's just bad data. I'm working on better importing of lexical information that avoids dumping and re-loading database fixtures with the lattice baked in.

**Comment by jtauber** [comment]
Closing as I think this is just bad data.
