### ISSUE TITLE
Lemma with numbers don't resolve properly to DCC

### ISSUE THREAD

**Issue by bilbe** [Hedera-Lang-Learn/hedera#47]
This is very important.

Lemmas that have numbers attached, e.g, sum1 and lego1 (very common words), aren't properly mapped to their entry in DCC Latin Core Vocabulary. I guess this shouldn't be a surprise, but we should fix this. It's very hard to make sentences that don't use "sum," i.e., "to be."

![image](https://user-images.githubusercontent.com/5712116/55750709-dff79780-5a11-11e9-817b-e9062b82776f.png)

![image](https://user-images.githubusercontent.com/5712116/55750508-6cee2100-5a11-11e9-806e-d2120f643d13.png)

Because of this in the Reader version I can't select my familiarity with the word:

![image](https://user-images.githubusercontent.com/5712116/55750945-75932700-5a12-11e9-8bdd-ab1fdc6c1f80.png)

That's "sum1" again. This works fine when the mapping works.

![image](https://user-images.githubusercontent.com/5712116/55751023-a8d5b600-5a12-11e9-8a57-9d7ee4729007.png)

**Comment by jtauber** [comment]
Ultimately the right way to solve this is to tweak the DCC data to use the numbers.

For example, the DCC `legō` is the Perseus/Logeion `lego2`.

**Comment by jtauber** [comment]
One thing I'm exploring, though is whether we can change the coverage code to consider it a match if the list has something higher up in the lattice, not necessarily the exact node. I think that will actually solve quite a few issues.

**Comment by jtauber** [comment]
My previous comment was addressed by #64; the rest by Ivy's spreadsheet
