### ISSUE TITLE
Student View: not remembering familiarity

### ISSUE THREAD

**Issue by bilbe** [Hedera-Lang-Learn/hedera#473]
So the Student view forgets a words familiarity as soon as you move away from it, but it does add it to your Personal Vocabulary. Plus if you go back and add the familiarity again, it add the word again to your Personal Vocabulary.

NB, this is working in PROD but broken in DEV.

On the up side, it is very smooth deleting the extra entry in the Personal Vocabulary view.

**Comment by IvyJL** [comment]
I think this is fixed now in dev. @bilbe , can you confirm?

**Comment by bilbe** [comment]
Yes. This is definitely fixed
