### ISSUE TITLE
Lemmatizing of filius

### ISSUE THREAD

**Issue by IvyJL** [Hedera-Lang-Learn/hedera#48]
filius is not recognized as being in the DCC core. It doesn’t seem to be a number issue.
![5F065839-4F84-4345-88E3-2926EA8A941A](https://user-images.githubusercontent.com/18600875/55766900-a8eea980-5a44-11e9-914d-ff38e1ae0291.png)

**Comment by jtauber** [comment]
The issue here (I think) is that this is the DCC entry:

```
"fīlia -ae f.; fīlius -ī m.","daughter; son","Noun: 1st Declension","The Household","909"
```

Seems like it would make sense to just split this into two entries manually before import.

**Comment by IvyJL** [comment]
Yes, I’ve been going through and splitting up a bunch of these “hidden” lemmata as I try to match things up with Morpheus.

**Comment by jtauber** [comment]
Addressed by Ivy's spreadsheet
