### ISSUE TITLE
Dev lemmatization progress bar broken

### ISSUE THREAD

**Issue by IvyJL** [Hedera-Lang-Learn/hedera#499]
Lost this on dev somehow. I have to reload the Texts page to see when lemmatization is done.

**Comment by bilbe** [comment]
This is still broken!

**Comment by bilbe** [comment]
Here's a text that you can use to reproduce the problem

Arma virumque canō, Trōiae quī prīmus ab ōrīs
Ītaliam, fātō profugus, Lāvīnia|que vēnit
lītora, multum ille et terrīs iactātus et altō
vī superum saevae memorem Iūnōnis ob īram;
multa quoque et bellō passus, dum conderet urbem,
inferretque deōs Latiō, genus unde Latīnum,
Albānī|que patrēs, atque altae moenia Rōmae.

**Comment by bilbe** [comment]
Not really fixed. 

Well, it better and it does finish, which is critical. However, I tried some longer texts and it seem not to truly "progress." It seems that it just has one position initially and then complete. It does the job but is kind of unsatisfying.

**Comment by arthurian** [comment]
The UX should be improved now with #521, which animates the progress bar between status updates so it doesn't just jump from like 27% complete to 100% complete (especially for shorter texts).

**Comment by bilbe** [comment]
This works now
