### ISSUE TITLE
hook up CI for styling checking at least

### ISSUE THREAD

**Issue by jtauber** [Hedera-Lang-Learn/hedera#5]
eventually tests but for now just having CI to check code style on PRs would be nice.

**Comment by arthurian** [comment]
FYI went ahead and setup a circleci project. Seems to be working with the default configuration, but it would be good to confirm in a PR.

**Comment by jtauber** [comment]
@arthurian sure, request away!

**Comment by jtauber** [comment]
I'm going to assume this is done. Reopen if not.
