### ISSUE TITLE
Bad math in the student view

### ISSUE THREAD

**Issue by bilbe** [Hedera-Lang-Learn/hedera#51]
If you add up those rows, they don't add to 100%. I think this happens when you switch your familiarity a few times with various words.

<img width="938" alt="image" src="https://user-images.githubusercontent.com/5712116/56680497-5bee1280-6695-11e9-9925-3b78f5b85748.png">

**Comment by paltman** [comment]
Yikes!  Let's fix that ASAP.

**Comment by paltman** [comment]
@bilbe i've been trying to reproduce but can't.  do you have specific steps for me to try?

**Comment by bilbe** [comment]
This is only a problem on dev: https://dev.hederaproject.org/lemmatized_text/2/learner/
It seems to work fine on prod: https://hederaproject.org/lemmatized_text/23/learner/

I'm just "show familiarity" and then find a word that I can set the familiarity. Then I just type 1,2,3,4,5,1,2,3,4,5 and the numbers go up. I'm not sure what the difference is between the two. Do you know @joshuagetega ?

**Comment by paltman** [comment]
That’s a lot for me to go on! Thanks. I’ll figure it out now, I’m sure.

**Comment by paltman** [comment]
I cannot reproduce on dev.

**Comment by paltman** [comment]
can someone get me a snapshot of the database?

**Comment by jtauber** [comment]
This has been fixed.
