### ISSUE TITLE
deal with enclitics in Latin

### ISSUE THREAD

**Issue by bilbe** [Hedera-Lang-Learn/hedera#57]
Enclitics are not being dealt with properly. Look at CLTK?

**Comment by jtauber** [comment]
Note: it is highly unlikely we'll get to this before the demo on 5/8 but we can definitely relook at tokenisation after that.

**Comment by bilbe** [comment]
FYI, I ran a little experiment using the CLTK for just tokenization. This did not yield anything, or at least didn't for enclitics. I think (and please correct me if I'm wrong) we want the enclitics to be separate tokens and not just stripped. When Morpheus lemmatizes, it strips them and so their existence is erased. This may be fine in some senses, but if memory serves we wanted to keep it as a separate lemma. We should check with Ivy though.

**Comment by jtauber** [comment]
I've just verified that the lemmatized text modeling can handle both multi-word tokens and clitics. I think we could expose this without complex tokenization logic by using a special character to mean a non-splitting space and another special character to mean a zero-width splitter. Let's discuss on our call.

**Comment by jtauber** [comment]
`amatus_est`    `virum|que`

**Comment by IvyJL** [comment]
For multi-word periphrastic verbs, these should be the relevant forms of "to be" (included archaic ones that might pop up in Plautus vel sim)
sum, es, est, sumus, estis, sunt
eram, eras, erat, eramus, eratis, erant
ero, eris, erit, erimus, eritis, erunt
sim, sis, sit, simus, sitis, sint
siem, sies, siet, siemus sietis, sient
essem, esses, esset, essemus, essetis, essent
forem, fores, foret, foremus, foretis, forent
esse, fuisse, iri, fore

**Comment by bilbe** [comment]
Perhaps not yet perfect, but very close. I'm closing this out
