### ISSUE TITLE
When resolving Latin est, only the “bare” Morpheus edo1 and sum1 appear

### ISSUE THREAD

**Issue by IvyJL** [Hedera-Lang-Learn/hedera#68]
We don’t see the sum entries from the vocab lists. Probably related to issue 47.
![A86CC557-97D4-438C-8430-BF5B9BEDD748](https://user-images.githubusercontent.com/18600875/57341724-9205aa80-7109-11e9-97cf-c3e4680c0422.png)

**Comment by jtauber** [comment]
as a workaround for tomorrow: when you select 2596 (sum1) does it have what you want as a parent? In other words can you navigate to what you want for now?

**Comment by jtauber** [comment]
Although it is odd that the DCC sum doesn't appear under sum1 (I wouldn't expect the Shelmerdine because it hasn't been linked to the morpheus yet).

**Comment by IvyJL** [comment]
Actually, I think it’s OK for tomorrow. If I select sum1, then the DCC sum appears and can be selected.

**Comment by paltman** [comment]
I'm not sure what to do on this.  If it is a source data issue, it's out of my area of expertise.  If we feel like this is a bug in _how_ we are consuming the data, I can definitely go on the hunt.

**Comment by bilbe** [comment]
I think what the algorithm should do is...
1. based on frequency data, it should choose sum1
2. sum1 should always lead to "lemma sum"
3. the user should be given the option of choosing "lemma edo," which is much less frequent but possible.
Look at the image below:
![image](https://user-images.githubusercontent.com/5712116/61819745-9f395800-ae21-11e9-9170-13599dceb406.png)

**Comment by IvyJL** [comment]
I think Bill has described the desired behavior upon seeing "est". 
neither sum1 nor edo1 should be visible to users.

Thanks,
Ivy

**Comment by bilbe** [comment]
NB: this is a thought experiment. 
This is where I feel like we need to have more metadata in the lattice nodes, e.g, **display: hidden**, which can be ignored in when needed. I know James has said that he doesn't want to add more information, but as I diagrammed things out, I started to realize the lattice is a way to represent graph database nodes(latticenode) and edges (latticenode_children) in a relational database. In which case, it may make sense to use the edges to not only hold the relationship vector, as it's already doing, but to hold frequency information or other aspects of the relationship.

Reworking the lattice from above it could looks something like this:
![image](https://user-images.githubusercontent.com/5712116/61879503-27bb0580-aec1-11e9-8a80-2e3318d0dfb9.png)
Note that the relationship vectors are different than the originals!

And the logic would  be as I suggested above, go something like this now:
find "ambiguous est" it is a hidden node
look at edges (latticenode_children) for frequency data and choose the higher number
"lemma sum1" is also hidden, so follow the vector to "lemma sum"
"lemma sum" has a display of true, so show this one.
if there were multiple branches descending from initial form, i.e., "ambiguous est" follow that branch too using the same logic and show in display for users to select

or something like that.

The dictionary entry links would be reduced to one by the user selecting the dictionary from a drop down list for the whole document.

Does that make sense? "Talk amongst yourselves."

**Comment by jtauber** [comment]
I think this can be closed.

When 'est' appears now, it results in the following:

```
est
    16868. edo or sum morpheus ambiguity
        5197. edo to eat, consume
        1. sum, esse, fuī to be, exist
```

which seems corrects.

**Comment by IvyJL** [comment]
This seems fixed when you first go to disambiguate an instance of _est_.
But when you select either _sum_ or _edo_, then a number of other options appear. See the images below. The specially odd thing about this is that if I mark the text as unresolved again, it doesn't go back to the original two choices.

But this is probably a separate issue, which I think we talked about before. So if a text has _est_, the choices should be _sum_ "to be" or _edo_ "to eat." And initially they are now.
But wen I select _edo_ "to eat" (which is edo2) as the right one, then I get all the "upstream" options, like the other edo "to put forth" (which is edo1).

![Screen Shot 2020-04-09 at 12 13 22 PM](https://user-images.githubusercontent.com/18600875/78916492-90500f80-7a5b-11ea-8041-b50e9b64bbdf.png)

![Screen Shot 2020-04-09 at 12 12 29 PM](https://user-images.githubusercontent.com/18600875/78916577-af4ea180-7a5b-11ea-8c72-35ad28e1884e.png)

![Screen Shot 2020-04-09 at 12 19 37 PM](https://user-images.githubusercontent.com/18600875/78917102-6b0fd100-7a5c-11ea-93ae-f72349fe874e.png)

**Comment by IvyJL** [comment]
I think this is fixed! Closing.
