### ISSUE TITLE
Separate Teacher and Learner

### ISSUE THREAD

**Issue by bilbe** [Hedera-Lang-Learn/hedera#72]
It's been great for demoing, but we need to separate teacher and learner experiences, but still have an admin role that will basically give us access to both like we have now.

**Comment by paltman** [comment]
Would it suffice to ask the user when they are signing up if they are a Teacher or a Learner?  We obviously need to model this and attach to the user account but not sure how we discern who is what.

**Comment by bilbe** [comment]
@IvyJLand @jtauber can you comment on this?

Here are my thoughts. I think it needs to be a role based on language, so I'm a teacher for German, but a student of Greek. That said, it is quite common for graduate students, high school teachers, and others to be teaching a language and studying it at the same time. I'm thinking that we want to think about how the tools are divided by role:

Student in a class:
- reading environment
- my vocabulary list 

Lifelong learner:
- reading environment
- my vocabulary list 
- evaluation tools

Teachers:
- reading environment
- evaluation tools
- class management
- class vocabulary list(s)

Language Admins:
- public text management
- public vocabulary management
- lattice management?

Super users:
- everything

**Comment by paltman** [comment]
@jtauber what do you think about us having a `Language` model that can drive a lot of this.

Even if it is just `Language(name, code)`, at least it's something that we can hang things off of like `Role` which in addition to linking to `Language` could also link a user with the 5 roles above.

Something like:

```python
class Language(models.Model):
    name = models.CharField(max_length=150)
    code = models.CharField(max_length=10)  # e.g. lat, grc, rus

    @property
    def service(self):
        pass  # construct and return service object 


class UserRole(models.Model):
    role = models.CharField(choices=ROLE_CHOICES)  # the 5 choices above
    language = models.ForeignKey(Language)
    user = models.ForeignKey(User)

    class Meta:
        unique_together = [('role', 'language', 'user')]  # user can have multiple intersecting roles
```

**Comment by paltman** [comment]
changed my mind on the `Language` model and instead am just going with moving the `LANGUAGES` constants to settings and then doing:

```python
from django.conf import settings
from django.db import models


LANG_CHOICES = [
    (lang, settings.HEDERA_LANGUAGES[lang])
    for lang in settings.HEDERA_LANGUAGES.keys()
]

ROLE_STUDENT = "student"
ROLE_LEARNER = "learner"
ROLE_TEACHER = "teacher"
ROLE_LANG_ADMIN = "langadmin"
ROLE_SUPER_ADMIN = "superadmin"

ROLE_CHOICES = [
    (ROLE_STUDENT, "Student in a Class"),
    (ROLE_LEARNER, "Lifelong Learner"),
    (ROLE_TEACHER, "Teacher"),
    (ROLE_LANG_ADMIN, "Language Admin"),
    (ROLE_SUPER_ADMIN, "Super user"),
]


class UserRole(models.Model):

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    role = models.CharField(max_length=10, choices=ROLE_CHOICES)
    lang = models.CharField(max_length=3, choices=LANG_CHOICES)

    class Meta:
        unique_together = [("user", "role", "lang")]
```

**Comment by paltman** [comment]
it seems like it might be a safe default to make everyone who signs up a `Student` or `Learner`
