### ISSUE TITLE
Tolkenization should be in the language-specific modules

### ISSUE THREAD

**Issue by bilbe** [Hedera-Lang-Learn/hedera#76]

**Comment by bilbe** [comment]
I was just talking to Artie and he mentioned that tokenization (splitting on white space only) is taking place in the main part of Hedera. I think this would make more sense in the language modules. I can think of lots of language-specific instances for tokenization, especially Chinese & Japanese.

**Comment by bilbe** [comment]
A note from Artie:

Hedera is currently tokenizing text in the lemmatization module, splitting on spaces and stripping basic punctuation.
 
See lemmatize_text() here:
 
https://github.com/Hedera-Lang-Learn/hedera/blob/1c8abb2bf88d8841dad8cc05677298fb3638d630/lemmatization/lemmatizer.py#L27
 
Which is called from the model here (as a job):
 
https://github.com/Hedera-Lang-Learn/hedera/blob/a8653b9c9511b7b25dd7162df89b15d38c35596c/lemmatized_text/models.py#L10
I wonder if we could extract the tokenization so that it delegates to the appropriate language service. Perhaps each service could provide a function named tokenize_text():
 
https://github.com/Hedera-Lang-Learn/hedera/blob/dev/lemmatization/services/morpheus.py
https://github.com/Hedera-Lang-Learn/hedera/blob/dev/lemmatization/services/clancydb.py
 
This would allow the service to call out to an API to do the tokenization (as in the case of Russian via “clancydb”), or implement it in place or call some library. There could be a default tokenization method in case the service does not provide one.

**Comment by paltman** [comment]
I think this makes a lot of sense and don't expect it to take me long at all.

**Comment by paltman** [comment]
@bilbe I've provided default implementations in both services (which are identical but can now easily be overridden when the default needs to change).
