### ISSUE TITLE
Error Page from people trying to sign up with email already in use

### ISSUE THREAD

**Issue by bilbe** [Hedera-Lang-Learn/hedera#79]
Artie tried to sign up for a Hedera account and got an ugly error message. We should just have a nice error page for this.

**Comment by paltman** [comment]
I'm seeing ![](http://img.paltman.com/169c6d/Screen%252520Shot%2525202019-07-17%252520at%2525202.26.09%252520PM.png)

**Comment by jtauber** [comment]
Is this still an issue or can we close?

**Comment by bilbe** [comment]
I think this is good.

**Comment by IvyJL** [comment]
I just tried to sign up again and I received a nice message saying that the address was in use, so this can be closed
