### ISSUE TITLE
We should keep the new lines in the text.

### ISSUE THREAD

**Issue by bilbe** [Hedera-Lang-Learn/hedera#80]
I added "Galileo, Sedereus Nuncius, r5"  (https://hederaproject.org/lemmatized_text/50/) to the Hedera and it should look like this so that it looks like the actual page:

> ASTRONOMICUS NUNCIUS
> OBSERVATIONES RECENS HABITAS 
> Novi Perspicilli beneficio in lunae facie, Lacteo circulo 
> Stellisque nebulosis, innumeris fixis, necnon in 
> quatuor Planetis
> MEDICEA SIDERA 
> nuncupatis, numquam conspectis adhuc continens,
> atque declarans.
> Magna equidem in hac exigua tractatione singulis de natura speculantibus inspicienda contemplandaque propono. Magna, inquam, tum ob rei ipsius præstantiam, tum ob inauditam per ævum novitatem, tum etiam propter Organum, cuius beneficio eadem sensui nostro obviam sese fecerunt.
> Magnum sane est, supra numerosam inerrantium Stellarum multitudinem, quæ naturali facultate in hunc usque diem conspici potuerunt, alias innumeras superaddere oculisque palam exponere, antehac conspectas nunquam, et quæ veteres ac notas plusquam supra decuplam multiplicitatem superent.
> Pulcherrimum atque visu iucundissimum est, lunare corpus, per sex denas fere terrestres semidiametros a nobis remotum, tam ex propinquo intueri, ac si per

**Comment by jtauber** [comment]
we'll need to retain the line break during tokenisation

**Comment by jtauber** [comment]
might be worth solving at the same time as some of the punctuation tokenisation changes
