### ISSUE TITLE
I want to connect up "nuncius" with "nuntius" in the lattice.

### ISSUE THREAD

**Issue by bilbe** [Hedera-Lang-Learn/hedera#81]
In "Galileo, Sedereus Nuncius, r5," although Heder generally did a good job parsing the text that "nuncius" is just "nuntius."

https://hederaproject.org/lemmatized_text/50/

We need a way to do that. 

On thought I had was that the user could click on the word and do a search to find the right lattice node to connect it to. This would then add a new node to the lattice.

**Comment by jtauber** [comment]
Is this really just part of #71? Or is this more for the teacher (I think #71 was more for the language admin)

I agree we need a lattice editor at least for language admins.

**Comment by jtauber** [comment]
I realise now this isn't #71 (it's not about editing the lattice, it's just about correcting / adding the lemmatisation). I agree that a search (typeahead) to find the right lattice node is the best solution.

**Comment by IvyJL** [comment]
I think I see and agree with what you’re saying. It’s really just a spelling variant, of which there are many (like nil and nihil for “nothing”.  But variants like this that are medieval (or perhaps just idiosyncratic) won’t be in Morpheus.

**Comment by bilbe** [comment]
This can't be done in the user interface, but the admins can do this pretty easily now. We probably need to do something about adding a large number of forms all at once, but I'm closing this one out.
